import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import {
  withAuthenticator,
  WithAuthenticatorProps,
} from "@aws-amplify/ui-react";

const inter = Inter({ subsets: ["latin"] });

const Home = ({ signOut, user }: WithAuthenticatorProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Hello {user?.username}</p>
          <p>
            Sign out <button onClick={signOut}>here</button>
          </p>
        </div>
        <div>
          <p>
            <Link href="/staticExample"> Link to static page example</Link>
          </p>
          <p>
            <Link href="/ssrExample"> Link to SSR example</Link>
          </p>
          <p>
            <Link href="/ssrExample"> Link to SSR example</Link>
          </p>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>
        </div>
      </main>
    </>
  );
};

export default withAuthenticator(Home, { hideSignUp: true });
